# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7bbee8f93861e96ac673fc72ca3d414d2b3a2c1974cc3c618417806d8a00bc3b3ff6d9eecf5a00764d974e614b230de677aa7256105842eddb155e6f0b0ab37

test:
  secret_key_base: 9bbe109fc966b29b6691e1260a313a64c43cbc6b922fe37a9d7253ad8190cc8017c0685de7823ee949d3f42ea66f6439f8db521a818480e1c6b3e2e97e8db65e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
